//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_potion_H
#define METASPRITE_potion_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define potion_TILE_ORIGIN 0
#define potion_TILE_W 8
#define potion_TILE_H 16
#define potion_WIDTH 8
#define potion_HEIGHT 8
#define potion_TILE_COUNT 8
#define potion_PALETTE_COUNT 1
#define potion_COLORS_PER_PALETTE 4
#define potion_TOTAL_COLORS 4
#define potion_PIVOT_X 4
#define potion_PIVOT_Y 4
#define potion_PIVOT_W 8
#define potion_PIVOT_H 8

BANKREF_EXTERN(potion)

extern const uint8_t potion_tiles[128];

#endif
